name: CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Installing packages
      run: npm ci

    - name: Deploy with gh-pages
      run: ./node_modules/.bin/gh-pages -d dist -u "${{ secrets.USERNAME }} <${{ secrets.EMAIL }}>"
